### ISSUE TITLE
issu with zerk script

### ISSUE THREAD

**Issue by Jajoss** [KKonaW/zerk-script#1]
hi, i tried this script on my toolbox, but when try with my zerk something's popped out

![bern](https://user-images.githubusercontent.com/88104860/127363021-b8931ea5-4461-444f-ada9-9726083829fb.png)
this popped out, i dont know how to fix it and to make the script run

hope you reply this asap :D thanks

**Comment by KKonaW** [comment]
How are you even alive if you can't figure that out?
